CREATE TABLE IF NOT EXISTS mds_instrument_catalog (
    instrument_id BIGINT NOT NULL,
    canonical_symbol VARCHAR(64) NOT NULL,
    asset_class VARCHAR(64) NOT NULL,
    base_currency VARCHAR(16),
    quote_currency VARCHAR(16),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_mds_instrument_catalog PRIMARY KEY (instrument_id),
    CONSTRAINT uk_mds_catalog_canonical_symbol UNIQUE (canonical_symbol)
);

CREATE TABLE IF NOT EXISTS mds_provider_instrument_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider VARCHAR(64) NOT NULL,
    provider_symbol VARCHAR(128) NOT NULL,
    instrument_id BIGINT NOT NULL,
    priority INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_mds_provider_instrument_mapping PRIMARY KEY (id),
    CONSTRAINT uk_mds_mapping_provider_symbol UNIQUE (provider, provider_symbol)
);
