spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finance
    username: finance
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 15000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    open-in-view: false



  task:
    scheduling:
      pool:
        size: 2 # Aynı anda çalışabilecek scheduler sayısı

  scheduler:
    market-price:
      delay-ms: 60000 # Default değeri buradan yönetiriim