spring:
  application:
    name: market-data-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

providers:
  binance:
    base-url: https://api.binance.com

scheduler:
  binance:
    delay-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

market:
  tracked-symbols:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - SOLUSDT
    - XRPUSDT
  provider: binance

resilience:
  retry:
    max-attempts: 3
    delay-ms: 500
  timeout:
    seconds: 3