server:
  port: 9090

app:
  security:
    jwt:
      issuer-uri: ${JWT_ISSUER_URI:http://localhost:8085/realms/finance}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.security.jwt.issuer-uri}

gateway:
  services:
    finance-base-uri: ${FINANCE_BASE_URI:http://localhost:8080}
    market-base-uri: ${MARKET_BASE_URI:http://localhost:8082}
    news-base-uri: ${NEWS_BASE_URI:http://localhost:8083}
    reporting-base-uri: ${REPORTING_BASE_URI:http://localhost:8084}
    analytics-base-uri: ${ANALYTICS_BASE_URI:http://localhost:8085}