package com.company.marketdataservice.history.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.Timestamp;
import java.time.Instant;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class FxRateHistoryRepositoryImplTest {

    private static JdbcTemplate jdbcTemplate;
    private static FxRateHistoryRepositoryImpl repository;

    private static final Instant DAY_START = Instant.parse("2026-05-01T00:00:00Z");
    private static final Instant NEXT_DAY = Instant.parse("2026-05-02T00:00:00Z");

    @BeforeAll
    static void initDatabase() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:spot_metal_fx;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE mds_fx_rate_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    instrument_id BIGINT,
                    canonical_symbol VARCHAR(64) NOT NULL,
                    base_currency VARCHAR(16) NOT NULL,
                    quote_currency VARCHAR(16) NOT NULL,
                    bid DECIMAL(24,8),
                    ask DECIMAL(24,8),
                    mid DECIMAL(24,8) NOT NULL,
                    provider VARCHAR(64) NOT NULL,
                    observed_at TIMESTAMP NOT NULL,
                    event_id UUID,
                    ingest_time TIMESTAMP NOT NULL
                )
                """);
        repository = new FxRateHistoryRepositoryImpl(jdbcTemplate);
    }

    @BeforeEach
    void cleanTable() {
        jdbcTemplate.execute("DELETE FROM mds_fx_rate_history");
    }

    @Test
    void deleteBySymbolProviderAndObservedAtBetween_removesMatchingRows() {
        jdbcTemplate.update(
                """
                        INSERT INTO mds_fx_rate_history
                            (canonical_symbol, base_currency, quote_currency, mid, provider, observed_at, ingest_time)
                        VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                        """,
                "XAUTRY",
                "XAU",
                "TRY",
                40000,
                "YAHOO_DERIVED_SPOT",
                Timestamp.from(DAY_START)
        );
        jdbcTemplate.update(
                """
                        INSERT INTO mds_fx_rate_history
                            (canonical_symbol, base_currency, quote_currency, mid, provider, observed_at, ingest_time)
                        VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                        """,
                "XAUTRY",
                "XAU",
                "TRY",
                204000,
                "MINTED_METAL_LBMA",
                Timestamp.from(DAY_START.plusSeconds(3600))
        );

        int deleted = repository.deleteBySymbolProviderAndObservedAtBetween(
                "XAUTRY",
                "YAHOO_DERIVED_SPOT",
                DAY_START,
                NEXT_DAY
        );

        assertEquals(1, deleted);
        Integer remaining = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM mds_fx_rate_history WHERE canonical_symbol = 'XAUTRY'",
                Integer.class
        );
        assertEquals(1, remaining);
    }
}
